### ISSUE TITLE
Allow Parameter to be longer then just one word (e.g. a question in quotation marks)

### ISSUE THREAD

**Issue by iStooge** [ibm-cloud-solutions/hubot-ibmcloud-nlc#105]
In my case I need the Classifier to get a parameter that is longer then one word, so it is not just an entity.
Is it possible that the NLC recognizes a parameter in longer form then just one word?
As in the last step of the conservation in the screenshot below.

Later i want hubot to be able to take a whole question as a parameter for example `"How can we solve the atomic waste problem?"` to save it as a question that is given to the users.

Is it perheps possible to mark the parameter with quotation marks as in my example? So that hubot recognizes this as parameter.

![image](https://cloud.githubusercontent.com/assets/7523006/20003586/98f9cb8a-a287-11e6-93df-5bf4efeb69dd.png)

**Comment by jlpadilla** [comment]
Check the repo https://github.com/ibm-cloud-solutions/hubot-ibmcloud-cognitive-entities
- If using quotes is acceptable for your application, maybe you can use a regular expression that matches all the text inside the quotes.
- If you have a list of all your possibilities, you could use the _fuzzyMatch_.  (Seems like maybe your "topics" would fit this).
- Finally, you should be able to provide your own _entityFunction_ in which you can define any logic necessary to extract your entities.

Maybe @JonHoughton has a better suggestion.

**Comment by JonHoughton** [comment]
@jlpadilla is correct that the `hubot-ibmcloud-cognitive-entities` is the repository that handles the entity processing.

The problem here is that even though you know that 'Car and Bike' is the entity value that you would like to end up with it is not clear how to tell the code that you wanted 'Car and Bike', 'Car', or 'Bike' when processing the line as a natural language string of text.

If there is a known set of entity values: 'Trees and Flowers', ..., and 'Cars and Bikes' then the best way to handle this is by seeding the set of known entities using `nlcconfig.updateGlobalParameterValues()` and/or `nlcconfig.setGlobalEntityFunction()`.  This allows the entity processing code to quickly find matching entities within the entered text and to provide fuzzy matching capabilities if the exact entity was not entered.

If the set of entity values is not known, then you might have to write your own entityFunction to extract the entity value from the entered text according to your own rules (e.g., text within double-quotes).

**Comment by iStooge** [comment]
@jlpadilla and @JonHoughton: Thank you for your feedback!
In my case I think I need to write my own entityFunction and just watch out for quotes. 
But I keep the fuzzyMatch in mind! Perheps it will fit one of the next scenarios.
Thank you :)
