### ISSUE TITLE
Command matching NLC.json entry doesn't match

### ISSUE THREAD

**Issue by clanzen** [ibm-cloud-solutions/hubot-ibmcloud-nlc#45]
When testing hubot-ibmcloud-service-management, I found that an entry in the NLC.json for binding a service, "Bind my Bluemix service" did NOT match the right command.  I was presented with the following instead.

[Med confidence] Please help me understand your request by selecting an option.
(0) [41.26%] Suggest a Bluemix service
(1) None of these options are correct.

At worst, it should be showing me the service bind command as an option alongside others.  Every other NLC.json entry I try in service-management appears to have the same issue.  So, it appears no training is happening.

**Comment by jlpadilla** [comment]
Most likely the root cause for this problem is that the NLC classifier isn't trained with the `hubot-ibmcloud-service-management` data, however, we don't have any possible way to debug it and confirm this theory. That's why I've created the enhancement request #56 to record the classifiers training data and provide a command to display it.

**Comment by jlpadilla** [comment]
@clanzen Can you confirm that this problem still exist? I've added a new feature that allows us to inspect the data used to train the classifier. (#56)

With the latest code
1. train a new classifier `nlc train`
2. Recreate the problem.
3. Inspect the data used for training `nlc data` or `nlc data service` to filter to the classification containing the word service.

**Comment by clanzen** [comment]
I verified the problem doesn't work when playing with the currently released IBMCloudBot
