### ISSUE TITLE
Bot not waiting for entity dialog input

### ISSUE THREAD

**Issue by jlpadilla** [ibm-cloud-solutions/hubot-ibmcloud-nlc#94]
In the conversation below, seems like both dialogs listen to the same input.

![image](https://cloud.githubusercontent.com/assets/4671325/18496798/ef0f1a98-79f6-11e6-9901-73d950310ebc.png)

**Comment by JonHoughton** [comment]
The problem seems to be with the use of Conversations in `hubot-ibmcloud-cognitiive-entities`.  It was creating a new Conversation on each call to getEntities() and using it throughout its processing.  But, this doesn't appear to be good enough.  After issuing various commands we eventually can get into a state in which the Conversations are confused and use input from another.  The fix is to use one Conversation for all processing within an instance of EntityManager.

This required two PRs:
https://github.com/ibm-cloud-solutions/hubot-ibmcloud-cognitive-entities/pull/12
https://github.com/ibm-cloud-solutions/hubot-ibmcloud-nlc/pull/95
